# ###################################################
# ##### this makefile was generated by chatgpt ######
# ########### don't expect much from it #############
# ###################################################

CXX := g++
CXXFLAGS := -std=c++20 -Wall -Wextra -g -MMD -MP
INCLUDES := -Iinclude

SRC_DIR := src
BUILD_DIR := build

SRC_FILES := $(shell find $(SRC_DIR) -name '*.cpp')
OBJ_FILES := $(patsubst $(SRC_DIR)/%.cpp,$(BUILD_DIR)/%.o,$(SRC_FILES))
DEP_FILES := $(OBJ_FILES:.o=.d)

TARGET := laddle

# Runtime search path: lib/ next to the executable
LDFLAGS := -Wl,-rpath,'$$ORIGIN/lib'
LDLIBS  := -lsfml-graphics -lsfml-audio -lsfml-window -lsfml-system

all: $(TARGET)

# Link
$(TARGET): $(OBJ_FILES)
	$(CXX) $(OBJ_FILES) -o $@ -L./lib $(LDFLAGS) $(LDLIBS)

# Compile
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp
	mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c $< -o $@

-include $(DEP_FILES)

clean:
	rm -rf $(BUILD_DIR) $(TARGET)

run: all
	./$(TARGET)

.PHONY: all clean run